name: unofficial_checkmk_monitoring
description: "Unofficial CheckMK Monitoring"

publish_to: 'none'

version: 1.0.11+11

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  http: ^1.2.1
  flutter_secure_storage: ^9.0.0
  flutter_local_notifications: ^18.0.1
  bcrypt: ^1.1.0
  intl: ^0.19.0
  flutter_datetime_picker: ^1.5.1
  flutter_timezone: ^3.0.1
  flutter_background: ^1.2.0
  flutter_svg: ^2.0.10
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.3
  timezone: ^0.10.0
  url_launcher: ^6.3.1
  encrypt: ^5.0.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/checkmk-icon-green.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "images/checkmk-icon-green.png"
    background_color: "#2C3843"
    theme_color: "#15D1A0"
  windows:
    generate: true
    image_path: "images/checkmk-icon-green.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "images/checkmk-icon-green.png"

flutter:
  uses-material-design: true
  assets:
    - images/
