name: ptp_4_monitoring_app
description: "checkmk for RH KÃ¶ln"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.0.5
  http: ^1.2.1
  flutter_secure_storage: ^9.0.0
  flutter_local_notifications: ^17.1.2
  bcrypt: ^1.1.0
  intl: ^0.19.0
  flutter_datetime_picker: ^1.5.1
  flutter_timezone: ^1.0.8
  url_launcher: ^6.2.0
  flutter_svg: ^2.0.0
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/checkmk-icon-green.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "images/checkmk-icon-green.png"
    background_color: "#2C3843"
    theme_color: "#15D1A0"
  windows:
    generate: true
    image_path: "images/checkmk-icon-green.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "images/checkmk-icon-green.png"

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
